version: '3.2'

services:
    delegator:
        build: backend/delegator
        ports:
            - "8000:8000"
        volumes:
            - ./backend/delegator:/app
            - ./backend/images:/images
        links:
            - runner1
            - runner2
    runner2:
        build: backend/runner
        ports:
            - "3000"
        volumes:
            - ./backend/runner:/app
            - ./backend/models:/models
    runner2:
        build: backend/runner
        ports:
            - "3000"
        volumes:
            - ./backend/runner:/app
            - ./backend/models:/models

