version: '3.2'

services:
    frontend:
        build: frontend
        ports:
            - "8000:8000"
        volumes:
            - ./frontend:/app
        links:
            - delegator
        restart: always
    delegator:
        build: backend/delegator
        ports:
            - "8000"
        volumes:
            - ./backend/delegator:/app
            - ./backend/images:/images
        links:
            - runner1
            - runner2
        restart: always
    runner1:
        build: backend/runner
        ports:
            - "3000"
        volumes:
            - ./backend/runner:/app
            - ./backend/models:/models
            - ./backend/images:/images
        restart: always
    runner2:
        build: backend/runner
        ports:
            - "3000"
        volumes:
            - ./backend/runner:/app
            - ./backend/models:/models
            - ./backend/images:/images
        restart: always
